### ISSUE TITLE
Introduce Installation Override to Disable Tracing for event-source [SKR Only]

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/control-plane#104]
With #[9040](https://github.com/kyma-project/kyma/pull/9040) disabling of tracing in event-source component has become configurable. Lets Introduce an override to disable tracing in provisioned kyma-runtimes, by default.

**AC**
- Provisioned Kyma Runtime should have tracing disabled

**Comment by sayanh** [comment]
This issue is invalidated as `HTTP_ADAPTER_TRACING_ENABLED` is getting removed in https://github.com/kyma-project/kyma/pull/9186/files#diff-f140dd105e22608b1365bb30da79cc12L28. I'd like to still validate whether disabling tracing in istio is enough to disable tracing in event-sources. Right now, this validation is blocked by https://github.com/kyma-project/kyma/pull/9186.

**Comment by anishj0shi** [comment]
Tracing config will now be controlled via istio's general configuration, which can be parameterised globally via a global installation override.
