### ISSUE TITLE
Upgrade operations could overwrite OIDC, admin list and autoscaler params

### ISSUE THREAD

**Issue by wozniakjan** [kyma-project/control-plane#1299]
**Description**

Message from @ebensom 

>Hi @gopher,
Am I thinking right that after the autoscaler params can be changed as part of SI update , this piece of code in cluster upgrade process is incorrect, as it overwrites operation.ProvisioningParameters (latest params obtained from instance) with the original ProvisioningParameters used during provisioning, so effectively undoing user changes in autoscaler settings.

https://github.com/kyma-project/control-plane/blob/7485d4eba7bd058ec0795bd258d7249504b7cdc6/components/kyma-environment-broker/internal/process/upgrade_cluster/initialisation.go#L118-L127

**Expected result**
n/a
**Actual result**
n/a
**Steps to reproduce**
n/a
**Troubleshooting**
n/a

**Comment by piotrmiskiewicz** [comment]
The upgrade cluster operation takes provisioning parameters instead of the newest (modified by an update).
AC:

provide a e2e unit test described below
Expected result

The following scenario is passing:

Provision SKR,
Update autoscaler params,
Trigger upgrade cluster
assert that cluster upgrade request contains autoscaler params set in previous step (2)
