### ISSUE TITLE
Integrate DependaBot to automate bumping our dependencies in KEB code

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#1472]
**Description**

Integrate DependaBot to automate bumping our dependencies in KEB code. Contact neighbors team as they already using that in some repositories.

**Reasons**

Keep our dependencies up to date. Reduce number of expired security issues.

**AC**

- [ ] integrate DependaBot to automate bumping our dependencies in KEB code
- [ ] find out if DependaBot would also take care of transitive dependencies

**Links**

- https://github.com/dependabot

**Comment by wozniakjan** [comment]
https://github.com/kyma-project/control-plane/pull/1494 should enable dependabot for KEB, wondering if we want to integrate this with anything else?

**Comment by wozniakjan** [comment]
> * [x] find out if DependaBot would also take care of transitive dependencies

partially, at the time of writing this, KEB had 146 identified dependencies in dependabot - https://github.com/kyma-project/control-plane/network/dependencies. However, there appear to be 899 dependencies in KEB total, including transitive deps

```
$ cat go.sum | awk '{print($1)}' | sort | uniq | wc -l
899
```

Also, dependabot will bump the dependency but will not create replace directives to overwrite the used dependency. A pattern that was sometimes necessary because KEBs transitive deps themself import an outdated release.

> * [x] integrate DependaBot to automate bumping our dependencies in KEB code

merged https://github.com/kyma-project/control-plane/issues/1472, and its already working:
* https://github.com/kyma-project/control-plane/pull/1496
* https://github.com/kyma-project/control-plane/pull/1500
