### ISSUE TITLE
Trial Plan - SKR on one node

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#287]
**Description**

We'd like to reduce costs for trials and with evaluation profile in the Kyma, https://github.com/kyma-project/kyma/issues/9673 we will be able to work on one node only.

**AC**
- Trial Kyma has 1 node 4CPU/ 16GB memory
- only one override passed to Kyma, --set global.kymaProfile=evaluation (in the context of CPU, memory and autoscalling)
- review overrides per runtime in the `management-plane-config` repo

**Comment by kjaksik** [comment]
We need to
- set proper profiles for plans (blocked by provisioner)
- set proper gardener defaults for TrialPlan (blocked by evaluation profile not finished)
- review overrides

**Comment by kjaksik** [comment]
KEB provides profiles for all Kyma versions, for the versions before profile support SKRs use the default overrides. Right now Trial SKRs still use 2 nodes since the test pipeline for evaluation profile is very unstable. Once the pipeline is fixed the number of nodes can be set to 1 using [this](https://github.com/kyma-project/control-plane/blob/master/resources/kcp/charts/kyma-environment-broker/values.yaml#L88) env.
