### ISSUE TITLE
Provisioner should not use static kubeconfig fetched from shoot

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/control-plane#3052]
**Description**

Provisioner should no longer fetch kubeconfig from shoot, and return it to the clients. The kubeconfig field should be removed from the API.

**Reasons**

Once Infrastructure Manager is introduced, and all Control Plane components's will stop using static kubeconfigs, the functionality should be removed from Provisioner.

**Comment by Disper** [comment]
This has dependency to
- [ ] Infrastructure Manager has to be promoted to PROD (internal issue no. 4877)
- [ ] https://github.com/kyma-project/control-plane/issues/3240 has to be fixed
- [ ] KEB has to no longer use provisioner's runtime status mutation (dependency on the above)

**Comment by Disper** [comment]
This one is not done. We're still populating the kubeconfig field but with a dynamic kubeconfig instead of a static kubeconfig. However as the only client of it - KEB is working fine with that, I believe that we could live with that additional field until we move the provisioning logic to the `infrastructure-manager` where any relevant data will be anyway stored in CR, and not in an external database.

**Comment by tobiscr** [comment]
DONE! Yiihaa
